- become: yes
  hosts: all
  tasks:
    - name: Get package
      shell: |
        sudo apt-get install openjdk-11-jdk-headless -y
        curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io.key | sudo tee /usr/share/keyrings/jenkins-keyring.asc > /dev/null
        echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/ | sudo tee /etc/apt/sources.list.d/jenkins.list > /dev/null
        sudo apt-get update -y
        sudo apt-get install jenkins -y

    - name: Start jenkins
      ansible.builtin.systemd:
        name: jenkins
        state: started

    - name: Copy script
      copy:
        src: ./create_job.sh
        dest: /etc/create_job.sh
        owner: root
        group: root
        mode: '0644'

    - name: Run crone job
      shell: echo */5 * * * * /etc/create_job.sh