
---
- become: yes
  hosts: all
  tasks:
    - name: Get package
      shell: |
        sudo apt-get install openjdk-11-jdk-headless -y
        curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io.key | sudo tee /usr/share/keyrings/jenkins-keyring.asc > /dev/null
        echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/ | sudo tee /etc/apt/sources.list.d/jenkins.list > /dev/null
        sudo apt-get update -y
        sudo apt-get install jenkins -y
        sudo wget http://localhost:8080/jnlpJars/jenkins-cli.jar

    - name: Start jenkins
      ansible.builtin.systemd:
        name: jenkins
        state: started

    - name: Copy script
      copy:
        src: ./create_job.sh
        dest: ./create_job.sh
        owner: vagrant
        group: vagrant
        mode: '777'

    - name: Copy job
      copy:
        src: ./job.xml
        dest: ./job.xml
        owner: vagrant
        group: vagrant
        mode: '777'

    - name: Create cron
      ansible.builtin.cron:
        name: Execute script
        state: present
        user: 'vagrant'
        minute: '*/2'
        hour: '*'
        day: '*'
        weekday: '*'
        month: '*'
        job: '~/create_job.sh'
